baseURL = 'http://shaderwit.ch/'
languageCode = 'en-us'
title = 'Shaderwit.ch - Unreal Engine render pipeline documentation and tutorials'
theme = 'hugo-theme-relearn'
Description = 'Shaderwit.ch is a website by Alessa \"Codekitten\" Baker and aims to teach Unreal Engine Shader Technical Art and document the Unreal Engine render architecture.'